=== jayengracio/Excelsior/src/comic.dtd
<!ELEMENT comic (panels)>
        <!ELEMENT panels (panel)>
        <!ELEMENT panel (above, left, right, below)>
        <!ELEMENT above (#PCDATA)>
        <!ELEMENT left (figure, balloon)>
        <!ELEMENT right (figure, balloon)>
        <!ELEMENT figure (appearance, skin, hair, lips, pose, facing)>
        <!ELEMENT appearance (#PCDATA)>
        <!ELEMENT skin (#PCDATA)>
        <!ELEMENT hair (#PCDATA)>
        <!ELEMENT lips (#PCDATA)>
        <!ELEMENT pose (#PCDATA)>
        <!ELEMENT facing (#PCDATA)>
        <!ELEMENT balloon (content)>
        <!ATTLIST balloon status CDATA "null">
        <!ELEMENT content (#PCDATA)>
        <!ELEMENT below (#PCDATA)>

=== jayengracio/Excelsior/src/comiXML.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<!DOCTYPE comic SYSTEM "comic.dtd">

<comic>
    <panels>
        <panel>
            <above></above>
            <left>
                <figure>
                    <appearance></appearance>
                    <skin></skin>
                    <hair></hair>
                    <lips></lips>
                    <pose></pose>
                    <facing></facing>
                </figure>
                <balloon>
                    <content></content>
                </balloon>
            </left>
            <right>
                <figure>
                    <appearance></appearance>
                    <skin></skin>
                    <hair></hair>
                    <lips></lips>
                    <pose></pose>
                    <facing></facing>
                </figure>
                <balloon>
                    <content></content>
                </balloon>
            </right>
            <below></below>
        </panel>
    </panels>
</comic>
